version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis-local
    command: ["redis-server", "--requirepass", "myStrongPassword"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8002:8001"
    restart: unless-stopped

volumes:
  redis_data:
